ALGORITMO
DECLARE B[100],SOMA,I,J,TERMO NUMÉRICO
PARA I←1 ATÉ 100 FAÇA
    INÍCIO
    ESCREVA "b(índice=",I,")"
    LEIA B[I]
    FIM
SOMA←0
PARA J←1 ATÉ 50 FAÇA
    INÍCIO
    TERMO←B[I]-B[101-1]
    TERMO←TERMO*TERMO*TERMO
    SOMA←SOMA+TERMO
    FIM
ESCREVA "Soma =",SOMA
FIM_ALGORITMO.
